
import Link from "next/link";

export default function TermsPage() {
    return (
        <div className="max-w-4xl mx-auto py-16 px-6">
            <h1 className="text-4xl font-bold mb-8 text-primary">Terms of Service</h1>
            <div className="prose dark:prose-invert max-w-none text-muted-foreground space-y-6">
                <p className="text-sm italic">Last Updated: January 14, 2026</p>

                <h3 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h3>
                <p>
                    By accessing and using Osera Design, you accept and agree to be bound by the terms and provision of this agreement.
                </p>

                <h3 className="text-xl font-semibold text-foreground">2. Service Usage</h3>
                <p>
                    You agree to use our AI generation services for lawful purposes only. Any content generated that violates local or international
                    laws is strictly prohibited.
                </p>

                <h3 className="text-xl font-semibold text-foreground">3. Intellectual Property</h3>
                <p>
                    The designs generated by you using Osera Design remain your intellectual property upon completed payment/credit deduction.
                </p>

                <h3 className="text-xl font-semibold text-foreground">4. Limitation of Liability</h3>
                <p>
                    Osera Design shall not be liable for any indirect, incidental, special, consequential or punitive damages resulting from your
                    access to or use of, or inability to access or use, the services.
                </p>

                <p className="mt-8 border-t pt-8">
                    Have questions? <Link href="/contact" className="text-primary hover:underline">Contact us</Link>.
                </p>
            </div>
        </div>
    );
}
