"use client";

import { useEffect, useState } from "react";
import { Sparkles, Image as ImageIcon, Download, Share2, Heart, Search, Filter } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { toast } from "sonner";
import Image from "next/image";

interface PublicDesign {
    id: string;
    imageUrl: string;
    prompt: string;
    aspectRatio: string;
    createdAt: string;
    user: {
        firstName: string | null;
        lastName: string | null;
    };
}

import Header from "@/app/(routes)/_common/header";

export default function TrendsPage() {
    const [designs, setDesigns] = useState<PublicDesign[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [searchQuery, setSearchQuery] = useState("");

    const fetchGallery = async () => {
        setIsLoading(true);
        try {
            const res = await fetch("/api/design/studio/gallery");
            if (res.ok) {
                const data = await res.json();
                setDesigns(data);
            }
        } catch (error) {
            console.error("Failed to fetch gallery", error);
            toast.error("Failed to load trending designs");
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => {
        fetchGallery();
    }, []);

    const filteredDesigns = designs.filter(d =>
        d.prompt.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (`${d.user.firstName} ${d.user.lastName}`).toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <div className="min-h-screen bg-background text-foreground selection:bg-primary/30">
            <Header />
            {/* Header / Hero */}
            <div className="relative overflow-hidden pt-20 pb-16">
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[500px] bg-gradient-to-b from-primary/20 to-transparent blur-3xl opacity-50 -z-10" />

                <div className="max-w-7xl mx-auto px-6 text-center space-y-6">
                    <Badge variant="outline" className="bg-primary/10 border-primary/30 text-primary px-4 py-1 rounded-full animate-in fade-in slide-in-from-bottom-3">
                        <Sparkles className="size-3 mr-2" /> Featured Trends
                    </Badge>
                    <h1 className="text-5xl md:text-7xl font-bold tracking-tighter bg-gradient-to-b from-foreground to-foreground/50 bg-clip-text text-transparent">
                        Discover the Future <br /> of Design.
                    </h1>
                    <p className="text-muted-foreground text-lg max-w-2xl mx-auto font-medium">
                        Explore high-fidelity posters and brand assets generated by the Osara Design community.
                    </p>

                    {/* Search Bar */}
                    <div className="max-w-xl mx-auto relative group pt-4">
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 size-5 text-muted-foreground group-focus-within:text-primary transition-colors" />
                        <Input
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            placeholder="Search trends by prompt or creator..."
                            className="w-full h-14 bg-secondary/50 border-border rounded-2xl pl-12 pr-4 focus:ring-2 focus:ring-primary transition-all text-base"
                        />
                    </div>
                </div>
            </div>

            {/* Gallery Grid */}
            <main className="max-w-7xl mx-auto px-6 pb-20">
                {isLoading ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {[1, 2, 3, 4, 5, 6].map((i) => (
                            <div key={i} className="aspect-[4/5] rounded-3xl bg-secondary animate-pulse" />
                        ))}
                    </div>
                ) : filteredDesigns.length === 0 ? (
                    <div className="text-center py-40 border-2 border-dashed border-border rounded-[3rem] bg-secondary/20">
                        <div className="size-20 bg-secondary rounded-full flex items-center justify-center mx-auto mb-6">
                            <ImageIcon className="size-10 text-muted-foreground" />
                        </div>
                        <h3 className="text-2xl font-bold mb-2">No trends found</h3>
                        <p className="text-muted-foreground max-w-xs mx-auto mb-8">
                            {searchQuery ? "Try a different search term." : "Be the first to feature a design from the Studio!"}
                        </p>
                        <Button variant="outline" className="rounded-full border-border hover:bg-secondary" onClick={() => setSearchQuery("")}>
                            Explore All
                        </Button>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {filteredDesigns.map((d) => (
                            <Card key={d.id} className="group relative aspect-[4/5] overflow-hidden rounded-[2rem] border-border bg-card shadow-2xl transition-all hover:translate-y-[-8px] hover:shadow-primary/10">
                                <Image
                                    src={d.imageUrl}
                                    alt={d.prompt}
                                    fill
                                    className="object-cover transition-transform duration-700 group-hover:scale-110"
                                />

                                {/* Overlay Controls */}
                                <div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 flex flex-col justify-between p-8">
                                    <div className="flex justify-between items-start">
                                        <Badge className="bg-white/10 backdrop-blur-md border-white/20 text-white uppercase tracking-tighter text-[10px]">
                                            {d.aspectRatio}
                                        </Badge>
                                        <div className="flex gap-2">
                                            <Button size="icon" variant="secondary" className="size-10 rounded-full bg-white/10 backdrop-blur-md border-white/10 hover:bg-white/20 text-white">
                                                <Heart className="size-4" />
                                            </Button>
                                            <Button size="icon" variant="secondary" className="size-10 rounded-full bg-white/10 backdrop-blur-md border-white/10 hover:bg-white/20 text-white">
                                                <Share2 className="size-4" />
                                            </Button>
                                        </div>
                                    </div>

                                    <div className="space-y-4">
                                        <p className="text-sm line-clamp-2 font-medium text-white/90 leading-tight">
                                            "{d.prompt}"
                                        </p>
                                        <div className="flex items-center justify-between pt-2 border-t border-white/10">
                                            <div className="flex items-center gap-2">
                                                <div className="size-8 rounded-full bg-primary flex items-center justify-center font-bold text-xs uppercase text-primary-foreground">
                                                    {d.user.firstName?.charAt(0) || "U"}
                                                </div>
                                                <span className="text-xs font-semibold text-white/70 tracking-tight">
                                                    By {d.user.firstName || "Anonymous"}
                                                </span>
                                            </div>
                                            <Button
                                                size="sm"
                                                className="bg-white text-black hover:bg-zinc-200 rounded-full font-bold px-4"
                                                onClick={() => {
                                                    const link = document.createElement('a');
                                                    link.download = `osera-trend-${d.id}.png`;
                                                    link.href = d.imageUrl;
                                                    link.click();
                                                }}
                                            >
                                                <Download className="size-4 mr-2" /> Get
                                            </Button>
                                        </div>
                                    </div>
                                </div>
                            </Card>
                        ))}
                    </div>
                )}
            </main>

            {/* CTA */}
            <section className="border-t border-border bg-secondary/30 backdrop-blur-md py-20 px-6 text-center">
                <div className="max-w-4xl mx-auto space-y-8">
                    <h2 className="text-4xl font-bold tracking-tight">Inspired to create your own?</h2>
                    <p className="text-muted-foreground max-w-lg mx-auto">
                        Join thousands of designers using Osara AI to transform their projects into professional brand assets.
                    </p>
                    <div className="flex flex-wrap items-center justify-center gap-4">
                        <Button size="lg" className="rounded-full bg-primary hover:opacity-90 px-8 h-14 font-bold text-lg" asChild>
                            <a href="/studio">Open Design Studio</a>
                        </Button>
                        <Button size="lg" variant="outline" className="rounded-full border-border hover:bg-secondary px-8 h-14 font-bold text-lg">
                            Learn More
                        </Button>
                    </div>
                </div>
            </section>
        </div>
    );
}
