"use client";

import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Quote } from "lucide-react";

const testimonials = [
    {
        name: "Ahmed Hassan",
        role: "Flutter Developer",
        location: "Cairo, Egypt",
        content: "This tool saved me days of work. I used to spend hours looking for inspiration, now Osara builds the base UI in seconds.",
        avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=100&h=100"
    },
    {
        name: "Sarah Miller",
        role: "Product Designer",
        location: "Dubai, UAE",
        content: "Finally an AI that understands mobile UI patterns. The designs are actually usable and clean. Highly recommended for startups.",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100&h=100"
    },
    {
        name: "Mohamed Ali",
        role: "Startup Founder",
        location: "Riyadh, KSA",
        content: "I pitched my idea to investors using screens generated by Osara. It made my MVP look professional without hiring a designer.",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100&h=100"
    }
];

export default function Testimonials() {
    return (
        <section className="py-24 bg-muted/30">
            <div className="container px-4 md:px-6 mx-auto">
                <div className="text-center mb-16 space-y-4">
                    <h2 className="text-3xl font-bold tracking-tighter md:text-4xl bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">
                        Loved by Developers & Founders
                    </h2>
                    <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
                        Join hundreds of creators building faster with Osara AI.
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
                    {testimonials.map((t, i) => (
                        <Card key={i} className="border-muted bg-card/50 hover:bg-card hover:shadow-lg transition-all duration-300 group">
                            <CardHeader className="flex flex-row items-center gap-4 pb-2">
                                <Avatar className="h-12 w-12 border-2 border-primary/10 group-hover:border-primary/50 transition-colors">
                                    <AvatarImage src={t.avatar} alt={t.name} />
                                    <AvatarFallback>{t.name[0]}</AvatarFallback>
                                </Avatar>
                                <div>
                                    <h3 className="font-semibold text-foreground">{t.name}</h3>
                                    <p className="text-xs text-muted-foreground">{t.role} • {t.location}</p>
                                </div>
                            </CardHeader>
                            <CardContent>
                                <Quote className="h-8 w-8 text-primary/10 mb-2 fill-primary/5" />
                                <p className="text-muted-foreground leading-relaxed">
                                    "{t.content}"
                                </p>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            </div>
        </section>
    );
}
